import 'package:flutter/foundation.dart';
import '../models/consignee_model.dart';
import '../repositories/consignee_repository.dart';
import '../repositories/storage_repository.dart';

// UI states for clean state management
enum ViewState { idle, loading, error }

// ViewModel: Handles all business logic for consignees
// Uses ChangeNotifier for Provider integration
class ConsigneeViewModel extends ChangeNotifier {
  final ConsigneeRepository _repository;
  final StorageRepository _storageRepository;

  // ─── State ────────────────────────────────────────────────────────────
  ViewState _state = ViewState.idle;
  List<ConsigneeModel> _consignees = [];
  String? _errorMessage;
  String _searchQuery = '';

  // ─── Constructors ─────────────────────────────────────────────────────
  ConsigneeViewModel({
    required ConsigneeRepository repository,
    required StorageRepository storageRepository,
  })  : _repository = repository,
        _storageRepository = storageRepository;

  // ─── Getters ──────────────────────────────────────────────────────────
  ViewState get state => _state;
  List<ConsigneeModel> get consignees => _searchQuery.isEmpty
      ? _consignees
      : _consignees.where((c) {
          final q = _searchQuery.toLowerCase();
          return c.fullName.toLowerCase().contains(q) ||
              c.phone.toLowerCase().contains(q) ||
              c.address.toLowerCase().contains(q);
        }).toList();
  String? get errorMessage => _errorMessage;
  bool get isLoading => _state == ViewState.loading;
  bool get hasError => _state == ViewState.error;

  // ─── Public Methods ────────────────────────────────────────────────────

  /// Load all consignees from database
  Future<void> loadConsignees() async {
    _state = ViewState.loading;
    notifyListeners();

    try {
      _consignees = await _repository.getAll();
      _state = ViewState.idle;
    } catch (e) {
      _state = ViewState.error;
      _errorMessage = e.toString();
    }
    notifyListeners();
  }

  /// Update search query (filters locally)
  void setSearchQuery(String query) {
    _searchQuery = query;
    notifyListeners();
  }

  /// Add a new consignee with optional document images
  /// [healthCardBytes] - raw bytes of health card image (null if none)
  /// [foodHandlerCardBytes] - raw bytes of food handler card image (null if none)
  Future<bool> addConsignee({
    required String fullName,
    required String phone,
    required String address,
    List<int>? healthCardBytes,
    List<int>? foodHandlerCardBytes,
    String? healthCardFileName,
    String? foodHandlerCardFileName,
  }) async {
    _state = ViewState.loading;
    notifyListeners();

    try {
      String? healthCardUrl;
      String? foodHandlerCardUrl;

      // Upload images if provided
      // Each file gets a unique name using timestamp to avoid collisions
      if (healthCardBytes != null && healthCardFileName != null) {
        healthCardUrl = await _storageRepository.uploadFile(
          fileBytes: healthCardBytes,
          fileName: '${DateTime.now().millisecondsSinceEpoch}_$healthCardFileName',
          folder: 'health-cards',
        );
      }

      if (foodHandlerCardBytes != null && foodHandlerCardFileName != null) {
        foodHandlerCardUrl = await _storageRepository.uploadFile(
          fileBytes: foodHandlerCardBytes,
          fileName: '${DateTime.now().millisecondsSinceEpoch}_$foodHandlerCardFileName',
          folder: 'food-handler-cards',
        );
      }

      // Create the consignee with image URLs
      // The URLs stored in database point to Supabase Storage
      final consignee = ConsigneeModel(
        id: '', // Will be generated by database
        fullName: fullName,
        phone: phone,
        address: address,
        healthCardUrl: healthCardUrl,      // Supabase Storage URL
        foodHandlerCardUrl: foodHandlerCardUrl, // Supabase Storage URL
      );

      await _repository.add(consignee);
      await loadConsignees(); // Refresh the list
      return true;
    } catch (e) {
      _state = ViewState.error;
      _errorMessage = e.toString();
      notifyListeners();
      return false;
    }
  }

  /// Update existing consignee
  /// If new images are provided, old ones are deleted from storage
  Future<bool> updateConsignee({
    required String id,
    required String fullName,
    required String phone,
    required String address,
    List<int>? healthCardBytes,
    List<int>? foodHandlerCardBytes,
    String? healthCardFileName,
    String? foodHandlerCardFileName,
  }) async {
    _state = ViewState.loading;
    notifyListeners();

    try {
      final existing = _consignees.firstWhere((c) => c.id == id);
      String? healthCardUrl = existing.healthCardUrl;
      String? foodHandlerCardUrl = existing.foodHandlerCardUrl;

      // If new health card image is provided:
      // 1. Delete old image from storage (clean up)
      // 2. Upload new image
      // 3. Store new URL
      if (healthCardBytes != null && healthCardFileName != null) {
        if (existing.healthCardUrl != null) {
          await _storageRepository.deleteFile(existing.healthCardUrl!);
        }
        healthCardUrl = await _storageRepository.uploadFile(
          fileBytes: healthCardBytes,
          fileName: '${DateTime.now().millisecondsSinceEpoch}_$healthCardFileName',
          folder: 'health-cards',
        );
      }

      // Same process for food handler card
      if (foodHandlerCardBytes != null && foodHandlerCardFileName != null) {
        if (existing.foodHandlerCardUrl != null) {
          await _storageRepository.deleteFile(existing.foodHandlerCardUrl!);
        }
        foodHandlerCardUrl = await _storageRepository.uploadFile(
          fileBytes: foodHandlerCardBytes,
          fileName: '${DateTime.now().millisecondsSinceEpoch}_$foodHandlerCardFileName',
          folder: 'food-handler-cards',
        );
      }

      final updated = ConsigneeModel(
        id: id,
        fullName: fullName,
        phone: phone,
        address: address,
        healthCardUrl: healthCardUrl,
        foodHandlerCardUrl: foodHandlerCardUrl,
      );

      await _repository.update(updated);
      await loadConsignees();
      return true;
    } catch (e) {
      _state = ViewState.error;
      _errorMessage = e.toString();
      notifyListeners();
      return false;
    }
  }

  /// Delete consignee and its uploaded files
  Future<bool> deleteConsignee(String id) async {
    _state = ViewState.loading;
    notifyListeners();

    try {
      final consignee = _consignees.firstWhere((c) => c.id == id);

      // Clean up uploaded files from storage
      if (consignee.healthCardUrl != null) {
        await _storageRepository.deleteFile(consignee.healthCardUrl!);
      }
      if (consignee.foodHandlerCardUrl != null) {
        await _storageRepository.deleteFile(consignee.foodHandlerCardUrl!);
      }

      // Delete from database
      await _repository.delete(id);
      await loadConsignees();
      return true;
    } catch (e) {
      _state = ViewState.error;
      _errorMessage = e.toString();
      notifyListeners();
      return false;
    }
  }

  /// Clear error state
  void clearError() {
    _state = ViewState.idle;
    _errorMessage = null;
    notifyListeners();
  }
}