name: Flutter Web Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build web release
      run: flutter build web --base-href "/Lending_system/" --release --no-tree-shake-icons

    - name: Deploy to GitHub Pages (Lending_system)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: DONNHER/Lending_system
        publish_dir: ./build/web
